airline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catalog'),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('flight/', include('flight.urls', namespace='flight'))
]

flight/urls.py
from django.urls import path

from .views import (
    # Anonymous Facade
    get_all_flights, get_flight_by_id, get_flights_by_parameters, get_all_airlines,
    get_airline_by_id, get_airline_by_parameters, get_all_countries, get_country_by_id,

    # Customer Facade
    update_customer,
    add_ticket,
    remove_ticket,
    get_my_tickets,

    # Airline Facade
    get_my_flights,
    update_airline,
    add_flight,
    update_flight,
    remove_flight,

    # Admin Facade
    get_all_customers,
    add_airline,
    add_customer,
    add_administrator,
    remove_airline,
    remove_customer,
    remove_administrator,

    # Custom Views
    SearchFlightView,
    CreateTicketView,
    UpdateTicketStatusView,
    TicketListView
    )


app_name = 'flight'

urlpatterns = [
    # Anonymous Facade
    path('all-flights/', get_all_flights, name='all_flights'),
    path('flight-by-id/<int:flight_id>', get_flight_by_id, name='flight_by_id'),
    path('flight-by-parameters/<int:origin_country_id>/<int:destination_country_id>/<str:date>',
         get_flights_by_parameters, name='flight_by_parameters'),
    path('all-airlines/', get_all_airlines, name='all_airlines'),
    path('airline-by-id/<int:airline_id>', get_airline_by_id, name='airline_by_id'),
    path('airlines-by-parameters/<str:company_name>', get_airline_by_parameters, name='airline_by_parameters'),
    path('all-countries/', get_all_countries, name='all_countries'),
    path('country-by-id/<int:country_id>', get_country_by_id, name='country_by_id'),

    # Customer Facade
    path('update-customer/<int:customer>', update_customer, name='update_customer'),
    path('add-ticket', add_ticket, name='add_ticket'),
    path('remove-ticket/<int:ticket_id>', remove_ticket, name='remove_ticket'),
    path('get-my-tickets', get_my_tickets, name='own_tickets'),

    # Airline Facade
    path('own-flights', get_my_flights, name='own_flights'),
    path('update_airline/<int:airline>', update_airline, name='update_airline'),
    path('add-flight', add_flight, name='add_flight'),
    path('update-flight/<int:flight>', update_flight, name='update_flight'),
    path('remove-flight/<int:flight>', remove_flight, name='remove_flight'),

    # Admin Facade
    path('all-customers', get_all_customers, name='all_customers'),
    path('add-airline', add_airline, name='add_airline'),
    path('add_customer', add_customer, name='add_customer'),
    path('add-administrator', add_administrator, name='add_administrator'),
    path('remove_airline/<int:airline>', remove_airline, name='remove_airline'),
    path('remove_customer/<int:customer>', remove_customer, name='remove_customer'),
    path('remove_administrator/<int:administrator>', remove_administrator, name='remove_administrator'),

    # Views
    path('search/', SearchFlightView.as_view(), name='search_flight'),
    path('ticket/create/<int:pk>', CreateTicketView.as_view(), name='create_ticket'),
    path('ticket/update/<int:pk>', UpdateTicketStatusView.as_view(), name='update_status_ticket'),
    path('ticket/list/', TicketListView.as_view(), name='list_ticket'),
]

flight/forms.py
from django import forms
import django_filters

from .models import Ticket, Flight, TicketStatus


class CreateTicketForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = "__all__"


class FlightFilter(django_filters.FilterSet):
    price__gt = django_filters.NumberFilter(field_name='price', lookup_expr='gt')
    price__lt = django_filters.NumberFilter(field_name='price', lookup_expr='lt')

    class Meta:
        model = Flight
        fields = ('company', 'origin', 'destination', 'price', 'departure_time', 'landing_time')


class TicketStatusUpdateForm(forms.ModelForm):
    # status = forms.ChoiceField(choices=TicketStatus.choices, required=True)

    class Meta:
        model = Ticket
        fields = ('status', )

flight/views.py
import json
from datetime import datetime

from django.contrib import messages
from django.urls import reverse_lazy
from django.forms.models import model_to_dict
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect, get_object_or_404
from django.core.serializers.json import DjangoJSONEncoder
from django.http.response import JsonResponse, HttpResponseForbidden

from .decorators import auth_view, CustomerRequired
from .forms import FlightFilter, TicketStatusUpdateForm
from .models import Flight, Company, Country, Ticket
from accounts.models import Customer, User, Administrator, Token


# Serializing Data As Json
# - serialize_queryset
# - serialize_model_obj

def serialize_queryset(queryset):
    return json.dumps(list(queryset), cls=DjangoJSONEncoder)


def serialize_model_obj(obj):
    return json.dumps(model_to_dict(obj), cls=DjangoJSONEncoder)


# Anonymous Facade
# - get_all_flight
# - get_flight_by_id
# - get_flights_by_parameters
# - get_all_airlines
# - get_airline_by_id
# - get_airline_by_parameters
# - get_all_countries
# - get_country_by_id
# - create_new_user

def get_all_flights(request):
    data = serialize_queryset(Flight.objects.all().values())
    return JsonResponse(data, safe=False)


def get_flight_by_id(request, flight_id):
    obj = get_object_or_404(Flight, id=flight_id)
    data = serialize_model_obj(obj)
    return JsonResponse(data, safe=False)


def get_flights_by_parameters(request, origin_country_id: int, destination_country_id: int, date: str):
    d = datetime.fromisoformat(date)
    objects = Flight.objects.get_flights_by_parameters(int(origin_country_id), int(destination_country_id), d).values()
    data = serialize_queryset(objects)
    return JsonResponse(data, safe=False)


def get_all_airlines(response):
    data = serialize_queryset(Company.objects.all().values())
    return JsonResponse(data, safe=False)


def get_airline_by_id(request, airline_id: int):
    obj = get_object_or_404(Company, id=airline_id)
    data = serialize_model_obj(obj)
    return JsonResponse(data, safe=False)


def get_airline_by_parameters(request, company_name: str):
    objects = Company.objects.get_airline_by_parameters(company_name).values()
    data = serialize_queryset(objects)
    return JsonResponse(data, safe=False)


def get_all_countries(request):
    data = serialize_queryset(Country.objects.all().values())
    return JsonResponse(data, safe=False)


def get_country_by_id(request, country_id: int):
    obj = get_object_or_404(Country, id=country_id)
    data = serialize_model_obj(obj)
    return JsonResponse(data, safe=False)


def create_new_user(user: dict):
    obj, created_user = Customer.objects.update_or_create(**user, defaults={'role': ''})
    return obj, created_user


# Customer Facade
# - update_customer (customer)
# - add_ticket (ticket)
# - remove_ticket (ticket)
# - get_my_tickets ()

@auth_view(method='POST')
def update_customer(request, customer: int):
    cus = get_object_or_404(Customer, id=customer)
    cus.first_name = request.POST.get('first_name', cus.first_name)
    cus.last_name = request.POST.get('last_name', cus.last_name)
    cus.address = request.POST.get('address', cus.address)
    cus.phone_number = request.POST.get('phone_number', cus.phone_number)
    cus.credit_card = request.POST.get('credit_card', cus.phone_number)
    cus.save()
    return JsonResponse({'message': 'Customer has been updated Successfully'})


@auth_view(method='POST')
def add_ticket(request):
    Ticket.objects.create(
        flight=get_object_or_404(Flight, id=int(request.POST.get('flight'))),
        customer=get_object_or_404(Customer, id=int(request.POST.get('customer')))
    )
    return JsonResponse({'message': 'Ticket has been created Successfully'})


@auth_view(method='POST')
def remove_ticket(request, ticket_id: int):
    obj = get_object_or_404(Ticket, id=ticket_id)
    token = get_object_or_404(Token, name=request.POST.get('token'))
    if obj.customer.user != token.user:
        return HttpResponseForbidden('You are not the owner of this company')
    obj.delete()
    return JsonResponse({'message': 'Ticket has been deleted Successfully'})


@auth_view(method='GET')
def get_my_tickets(request):
    token = get_object_or_404(Token, name=request.GET.get('token'))
    tickets = Ticket.objects.filter(customer__user=token.user)
    data = serialize_queryset(tickets.values())
    return JsonResponse(data, safe=False)


# Airline Facade
# - get_my_flights ()
# - update_airline (airline)
# - add_flight (flight)
# - update_flight (flight)
# - remove_flight (flight)

@auth_view(method='GET')
def get_my_flights(request):
    token = get_object_or_404(Token, name=request.GET.get('token'))
    flights = Flight.objects.filter(company__manager=token.user)
    data = serialize_queryset(flights.values())
    return JsonResponse(data, safe=False)


@auth_view(method='POST')
def update_airline(request, airline: int):
    obj = get_object_or_404(Company, id=airline)
    token = get_object_or_404(Token, name=request.POST.get('token'))
    if obj.manager != token.user:
        return HttpResponseForbidden('You are not the owner of this company')
    obj.name = request.POST.get('name', obj.name)
    obj.country = get_object_or_404(Country, id=int(request.POST.get('country', obj.country.id)))
    obj.save()
    return JsonResponse({'message': 'Airline Company Has Updated Successfully'}, safe=False)


@auth_view(method='POST')
def add_flight(request):
    token = get_object_or_404(Token, name=request.POST.get('token'))
    customer = token.user
    Flight.objects.create(
        company=customer.manager,
        origin=get_object_or_404(Country, id=int(request.POST.get('origin'))),
        destination=get_object_or_404(Country, id=int(request.POST.get('destination'))),
        departure_time=datetime.fromisoformat(request.POST.get('departure_time')),
        landing_time=datetime.fromisoformat(request.POST.get('landing_time')),
        num_of_tickets=int(request.POST.get('num_of_tickets', 10))
    )
    return JsonResponse({'message': 'Airline Company Has Updated Successfully'}, safe=False)


@auth_view(method='POST')
def update_flight(request, flight: int):
    token = get_object_or_404(Token, name=request.POST.get('token'))
    flight = get_object_or_404(Flight, id=flight)
    if flight.company.manager != token.user:
        return HttpResponseForbidden('Your company is not the owner of this flight')
    flight.origin = get_object_or_404(Country, id=int(request.POST.get('origin', flight.origin.id)))
    flight.destination = get_object_or_404(Country, id=int(request.POST.get('destination', flight.destination.id)))
    flight.departure_time = datetime.fromisoformat(request.POST.get('departure_time', str(flight.departure_time)))
    flight.landing_time = datetime.fromisoformat(request.POST.get('landing_time', str(flight.landing_time)))
    flight.num_of_tickets = int(request.POST.get('num_of_tickets', flight.num_of_tickets))
    flight.save()
    return JsonResponse({'message': 'Flight Has Updated Successfully'}, safe=False)


@auth_view(method='POST')
def remove_flight(request, flight: int):
    token = get_object_or_404(Token, name=request.POST.get('token'))
    obj = get_object_or_404(Flight, id=flight)
    if obj.company.manager != token.user:
        return HttpResponseForbidden('Your company is not the owner of this flight')
    obj.delete()
    return JsonResponse({'message': 'Flight has been deleted Successfully'})


# Admin Facade
# - get_all_customers()
# - add_airline (...)
# - add_customer (...)
# - add_administrator (...)
# - remove_airline (airline)
# - remove_customer (customer)
# - remove_administrator (administrator)

@auth_view(method='GET', allow_admin_only=True)
def get_all_customers(request):
    data = serialize_queryset(Customer.objects.all().values())
    return JsonResponse(data, safe=False)


@auth_view(method='POST', allow_admin_only=True)
def add_airline(request):
    Company.objects.create(
        name=request.POST.get('name'),
        manager=get_object_or_404(User, username=request.POST.get('manager')),
        country=get_object_or_404(Country, id=request.POST.get('country'))
    )
    return JsonResponse({'message': 'Airline Has Been Added Successfully'}, safe=False)


@auth_view(method='POST', allow_admin_only=True)
def add_customer(request):
    Customer.objects.create(
        user=get_object_or_404(User, username=request.POST.get('user')),
        first_name=request.POST.get('first_name'),
        last_name=request.POST.get('last_name'),
        address=request.POST.get('address'),
        phone_number=request.POST.get('phone_number'),
        credit_card=request.POST.get('credit_card')
    )
    return JsonResponse({'message': 'Customer Has Been Added Successfully'}, safe=False)


@auth_view(method='POST', allow_admin_only=True)
def add_administrator(request):
    Administrator.objects.create(
        user=get_object_or_404(User, username=request.POST.get('user')),
        first_name=request.POST.get('first_name'),
        last_name=request.POST.get('last_name')
    )
    return JsonResponse({'message': 'Administrator Has Been Added Successfully'}, safe=False)


@auth_view(method='POST', allow_admin_only=True)
def remove_airline(request, airline: int):
    obj = get_object_or_404(Company, id=airline)
    obj.delete()
    return JsonResponse({'message': 'Airline has been deleted Successfully'})


@auth_view(method='POST', allow_admin_only=True)
def remove_customer(request, customer: int):
    obj = get_object_or_404(Customer, id=customer)
    obj.delete()
    return JsonResponse({'message': 'Customer has been deleted Successfully'})


@auth_view(method='POST', allow_admin_only=True)
def remove_administrator(request, administrator: int):
    obj = get_object_or_404(Administrator, id=administrator)
    obj.delete()

templates/flight/create.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
{% include 'base/admin_style.html' %}
<form method="POST" class="contact-form" style="width:65%; align:center; margin: 0 auto; margin-top:35px;">
    <h4 style="text-align:center;">{{ title }}</h4>
    <table class="table table-striped" style="margin: 0 auto; width: 80%">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Company</th>
            <th scope="col">Origin</th>
            <th scope="col">Destination</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Landing Time</th>
            <th scope="col">Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ flight.company }}</td>
            <td>{{ flight.origin }}</td>
            <td>{{ flight.destination }}</td>
            <td>{{ flight.departure_time }}</td>
            <td>{{ flight.landing_time }}</td>
            <td>{{ flight.price }}</td>
        </tr>
        </tbody>
    </table>
    <label for="credit_card">Credit Card:</label>
    <input class="form-control" type="text" pattern="^[0-9]{16}$" name="credit_card" id="credit_card" required>
    <div class="d-grid" style="margin-top:10px;">
        <button class="btn btn-dark btn-lg " id="submitButton" type="submit">Book</button>
    </div>
</form>
{% endblock %}

templates/flight/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    {% if tickets %}
        <table class="table table-striped" style="margin: 0 auto; width: 80%">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Company</th>
                <th scope="col">Origin</th>
                <th scope="col">Destination</th>
                <th scope="col">Departure Time</th>
                <th scope="col">Landing Time</th>
                <th scope="col">Price</th>
                <th scope="col">Status</th>
                <th scope="col">Link</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ ticket.flight.company }}</td>
                    <td>{{ ticket.flight.origin }}</td>
                    <td>{{ ticket.flight.destination }}</td>
                    <td>{{ ticket.flight.departure_time }}</td>
                    <td>{{ ticket.flight.landing_time }}</td>
                    <td>{{ ticket.flight.price }}</td>
                    <td>{{ ticket.status }}</td>
                    <td><a href="{% url 'flight:update_status_ticket' ticket.id %}"> Update</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <span style="color: red"> No Tickets Yet</span>
    {% endif %}
{% endblock %}

templates/flight/search.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
{% include 'base/admin_style.html' %}
    <form method="GET" class="contact-form" style="width:65%; align:center; margin: 35px auto 0;">
        <h4 style="text-align:center;">{{ title }}</h4>
        {{ filterset.form.media }}
        {{ filterset.form }}
        <button class="btn btn-dark btn-lg" id="submitButton" type="submit" style="right: 0; margin: 10px;">Search</button>
    </form>
    {% if filterset.qs %}
    <table class="table table-striped" style="margin: 0 auto; width: 80%">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Company</th>
            <th scope="col">Origin</th>
            <th scope="col">Destination</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Landing Time</th>
            <th scope="col">Price</th>
            <th scope="col">Link</th>
        </tr>
        </thead>
        <tbody>
        {% for flight in filterset.qs %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ flight.company }}</td>
            <td>{{ flight.origin }}</td>
            <td>{{ flight.destination }}</td>
            <td>{{ flight.departure_time }}</td>
            <td>{{ flight.landing_time }}</td>
            <td>{{ flight.price }}</td>
            <td><a href="{% url  'flight:create_ticket' flight.pk %}"> Book</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
{% endblock %}

templates/flight/update.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<form method="POST" class="contact-form" style="width:65%; align:center; margin: 0 auto; margin-top:35px;">
   <h4 style="text-align:center;">{{ title }}</h4>
   {% csrf_token %}
   {{ form }}
   <div class="d-grid" style="margin-top:10px;">
       <button class="btn btn-dark btn-lg " id="submitButton" type="submit">Submit</button>
   </div>
</form>
{% endblock %}